name: lanegcn
channels:
- defaults
- conda-forge
- pytorch
dependencies:
- python=3.8
- colour
- descartes
- imageio
- h5py
- hydra-core=1.1.0
- lap
- matplotlib
- motmetrics>=1.1
- numba
- numpy=1.19
- omegaconf=2.1
- opencv>=4.1.0
- pandas>=0.1.0
- pillow
- pyntcloud>=0.1.0
- scipy>=1.4.0
- conda-forge::shapely
- tqdm
- typing_extensions
- pytorch==1.5.1
- torchvision
- cudatoolkit=10.2
- cmake
- scikit-image
- IPython
- tqdm
- ipdb
- pip
- pip:
    - C:\Users\bey1abt\PycharmProjects\argoverse-api